export const RSA_PUBLIC_PEM_LABEL = 'RSA PUBLIC KEY';
export const RSA_PRIVATE_PEM_LABEL = 'RSA PRIVATE KEY';

export const ED25519_PUBLIC_PEM_LABEL = 'ED25519 PUBLIC KEY';
export const ED25519_PRIVATE_PEM_LABEL = 'ED25519 PRIVATE KEY';

export const SIGNING_ALGOS = ['RSA', 'ED25519', 'ECDSA'];
